version: '3'
services:
  jenkins:
    container_name: jenkins
    hostname: jenkins
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    ports:
      - "8080"
      - "8443"
      - "50000"
    networks:
      - front-tier
    volumes:
      - jenkins:/var/jenkins_home
      - /run/docker.sock

  gogs:
    container_name: gogs
    hostname: gogs
    build:
      context: ./gogs
      dockerfile: Dockerfile
    ports:
      - "10022"
      - "3000"
    networks:
      - front-tier
      - back-tier
    volumes:
      - gogs:/data
    depends_on:
      - db

  db:
    image: postgres:10
    container_name: "db"
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pg_password
      - POSTGRES_DB=pg_db
    ports:
      - "5432"
    networks:
      - back-tier
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  jenkins:
    external: true
  gogs:
    external: true
  db-data:
    external: true
